website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from .models import Meeting, User
from . import db

views = Blueprint("views", __name__)

# login route that handles the login form
@views.route("/", methods=["GET", "POST"])
@login_required
def home():
    if request.method == "POST":
        title = request.form.get("meeting")
        topic = request.form.get("topic")
        attendees = request.form.get("absentees")
        raised_by = request.form.get("raised_by")
        actions_required = request.form.get("actions_required")
        actioned_by = request.form.get("actioned_by")
        subsequent_information = request.form.get("subsequent_information")
        end_time = request.form.get("end_time")

        if len(title) < 1:
            flash("Please enter a title.", category="error")
        elif len(topic) < 1:
            flash("Please enter a topic.", category="error")
        elif len(attendees) < 1:
            flash("Please enter the attendees.", category="error")
        elif len(raised_by) < 1:
            flash("You cannot leave the raised by field empty.", category="error")
        elif len(actions_required) < 1:
            flash("Please enter the actions required.", category="error")
        elif len(actioned_by) < 1:
            flash("Please enter the actioned by.", category="error")
        elif len(subsequent_information) < 1:
            flash("Please enter any subsequent information.", category="error")
        elif len(end_time) < 1:
            flash("Please specify the date of completion.", category="error")
        else:
            # add to database
            new_meeting = Meeting(
                title=title,
                topic=topic,
                attendees=attendees,
                raised_by=raised_by,
                actions_required=actions_required,
                actioned_by=actioned_by,
                subsequent_information=subsequent_information,
                end_time=end_time,
                user_id=current_user.id,
            )
            db.session.add(new_meeting)
            db.session.commit()
            flash("Meeting added successfully.", category="success")
    return render_template("home.html", user=current_user)


# function for searching meetings
@views.route("/search", methods=["GET", "POST"])
@login_required
def search():
    if request.method == "POST":
        search_term = request.form.get("search_term")
        meetings = Meeting.query.filter(Meeting.title.contains(search_term)).all()
        flash("Search results for: {}".format(search_term), category="success")
        return render_template("search.html", meetings=meetings, user=current_user)
    else:
        meetings = Meeting.query.all()
        return render_template("search.html", meetings=meetings, user=current_user)


# function for delete modal
@views.route("/delete/<int:id>", methods=["POST"])
@login_required
def delete_meeting(id):
    meeting = Meeting.query.get_or_404(id)
    db.session.delete(meeting)
    db.session.commit()
    return render_template("minutes.html", user=current_user)


# function to edit meeting
@views.route("/edit/<int:id>", methods=["GET", "POST"])
@login_required
def edit_meeting(id):
    meeting = Meeting.query.get_or_404(id)
    if request.method == "POST":
        title = request.form.get("title")
        topic = request.form.get("topic")
        attendees = request.form.get("attendees")
        raised_by = request.form.get("raised_by")
        actions_required = request.form.get("actions_required")
        actioned_by = request.form.get("actioned_by")
        subsequent_information = request.form.get("subsequent_information")
        end_time = request.form.get("end_time")

        if len(title) < 1:
            flash("Please enter a title.", category="error")
        elif len(topic) < 1:
            flash("Please enter a topic.", category="error")
        elif len(attendees) < 1:
            flash("Please enter the attendees.", category="error")
        elif len(raised_by) < 1:
            flash("You cannot leave the raised by field empty.", category="error")
        elif len(actions_required) < 1:
            flash("Please enter the actions required.", category="error")
        elif len(actioned_by) < 1:
            flash("Please enter the actioned by.", category="error")
        elif len(subsequent_information) < 1:
            flash("Please enter any subsequent information.", category="error")
        elif len(end_time) < 1:
            flash("Please specify the date of completion.", category="error")
        else:
            # add to database
            meeting.title = title
            meeting.topic = topic
            meeting.attendees = attendees
            meeting.raised_by = raised_by
            meeting.actions_required = actions_required
            meeting.actioned_by = actioned_by
            meeting.subsequent_information = subsequent_information
            meeting.end_time = end_time
            db.session.commit()
            flash("Meeting updated successfully.", category="success")
            return render_template("minutes.html", meeting=meeting, user=current_user)


# @views.route("/delete-note", methods=["POST"])
# def delete_note():
#    note = json.loads(request.data)
#    noteId = note["noteId"]
#    note = Note.query.get(noteId)
#    if note:
#       if note.user_id == current_user.id:
#           db.session.delete(note)
#            db.session.commit()
#    return jsonify({})

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <style>
      body {
        background-color: #EC5766;
      }
      .container {
        background-color: white;
        border-radius: 10px;
        padding: 20px;
        margin-top: 20px;
        margin-bottom: 20px;
      }
      .form-control {
        border-radius: 10px;
      }
      .form-group {
        margin-bottom: 20px;
      }
      .btn {
        border-radius: 10px;
      }
      .btn-primary {
        background-color: #0066ff;
      }
      .btn-primary:hover {
        background-color: #0066ff;
      }
      .btn-primary:active {
        background-color: #0066ff;
      }
      .btn-primary:focus {
        background-color: #0066ff;
      }
      .btn-primary:active:hover {
        background-color: #0066ff;
      }
      .btn-primary:active:focus {
        background-color: #0066ff;
      }
      .btn-primary:active:focus:hover {
        background-color: #0066ff;
      }
      .btn-primary:focus:hover {
        background-color: #0066ff;
      }

    </style>
  <body>
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav center">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class ="nav-item nav-link" id="minutes" href="/minutes">View Minutes</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
  </body>
</html>

website/templates/home.html
{% extends "base.html" %} 

{% block title %}Home{% endblock %} 

{% block head %}
    <script src="/static/index.js"></script>
{% endblock %}

{% block content%}
</ul>
<br/>
<h1 align = "center">Meeting Minutes</h1>
<form action ="{{ url_for("views.home")}}" method="post">
  <div id = "meeting-minutes">
    <div>
      <label for="meeting">Title:</label>
      <input type="text" class="form-control" id="meeting" name = "meeting" placeholder="Enter meeting title:" maxlength="30">
    </div>
    <div>
      <label for="Topic">Topic</label>
      <input type="text" class="form-control" id="topic" name = "topic" placeholder="Enter topic:" maxlength="50">
    </div>
    <div>
      <label for="time">Date & Time:</label>
      <input type="datetime-local" class="form-control" id="time" name = "time" placeholder="Enter date:">
    </div>
    <div>
      <label for="absentees">Absentees:</label>
      <input type="text" class="form-control" id="absentees" name = "absentees" placeholder="Enter abseentee(s):">
    </div>
    <div>
      <label for="raised_by">Raised by:</label>
      <input type="text" class="form-control" id="raised_by" name = "raised_by" placeholder="Raised by:">
    </div>
    <div>
      <label for="actions-required">Actions required:</label>
      <textarea class="form-control" rows="5" id="actions_required" name = "actions_required" placeholder="Enter actions:"></textarea>
    </div>
    <div>
      <label for="actioned-by">Actioned by:</label>
      <input type ="text" class="form-control" id="actioned_by" name = "actioned_by" placeholder="Actioned by:">
    </div>
    <div>
      <label for="subsequent-information">Subsequent information:</label>
      <textarea class="form-control" rows="5" id="subsequent_information" name = "subsequent_information" placeholder="Enter subsequent information:"></textarea>
    </div>
    <div>
      <label for="endTime">Date of completion:</label>
      <input type="datetime-local" class="form-control" id="end_time" name = "end_time" placeholder="Enter date:">
    </div>
    <br/>
    <div class = "text-center">
      <!-- Submit data button -->
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
    <br/>
</form>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
    %}
    <form method="POST">
      <br/>
      <h1 align="center">Login</h1>
      <br/>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          placeholder="Enter password"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
    {% endblock %}

website/templates/minutes.html
{% extends "base.html" %} {% block title %}Minutes{% endblock %} 

{% block content%}
<br/>
<h1 align = "center"> View Your Meeting Minutes</h1>
<br/>
  <table class="table table-striped center">
    <thead>
      <tr>
        <th>Title:</th>
        <th>Topic:</th>
        <th>Date:</th>
        <th>Absentees:</th>
        <th>Raised by:</th>
        <th>Actions required:</th>
        <th>Actioned by:</th>
        <th>Subsequent information:</th>
        <th>Date of completion:</th>
        <th>Delete row:</th>
        <th>Edit row:</th>
      </tr>
    </thead>
    <tbody>
      {% for meeting in user.meetings %}
      <tr>
        <th scope="row" id="title" name="title">{{ meeting.title }}</th>
        <td>{{ meeting.topic }}</td>
        <td>{{ meeting.time }}</td>
        <td>{{ meeting.attendees }}</td>
        <td>{{ meeting.raised_by }}</td>
        <td>{{ meeting.actions_required }}</td>
        <td>{{ meeting.actioned_by }}</td>
        <td>{{ meeting.subsequent_information }}</td>
        <td>{{ meeting.end_time }}</td>
        <td>
        <!--button to delete meeting row on table-->
          <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal{{ meeting.id }}">
            Delete
          </button>
          <!--modal to confirm delete-->
          <div class="modal fade" id="deleteModal{{ meeting.id }}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="deleteModalLabel">Delete Meeting</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  Are you sure you want to delete this meeting?
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <form action="{{ url_for('views.delete_meeting', id=meeting.id) }}" method="post">
                  <button type="submit" class="btn btn-danger">Delete</button>
                </form>
              </div>
            </div>
          </div>
      </td>
      <td>
        <!--button to edit meeting row on table-->
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#editModal{{ meeting.id }}">
          Edit
        </button>
        <!--modal to edit meeting row-->
        <div class="modal fade" id="editModal{{ meeting.id }}" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="editModalLabel">Edit Meeting</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form action="{{ url_for('views.edit_meeting', id=meeting.id) }}" method="post">
                  <div class="form-group">
                    <label for="title">Title:</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ meeting.title }}">
                  </div>
                  <div class="form-group">
                    <label for="topic">Topic:</label>
                    <input type="text" class="form-control" id="topic" name="topic" value="{{ meeting.topic }}">
                  </div>
                  <div class="form-group">
                    <label for="attendees">Attendees:</label>
                    <input type="text" class="form-control" id="attendees" name="attendees" value="{{ meeting.attendees }}">
                  </div>
                  <div class="form-group">
                    <label for="time">Time:</label>
                    <input type="text" class="form-control" id="time" name="time" value="{{ meeting.time }}">
                  </div>
                  <div class="form-group">
                    <label for="raised_by">Raised by:</label>
                    <input type="text" class="form-control" id="raised_by" name="raised_by" value="{{ meeting.raised_by }}">
                  </div>
                  <div class="form-group">
                    <label for="actions_required">Actions required:</label>
                    <input type="text" class="form-control" id="actions_required" name="actions_required" value="{{ meeting.actions_required }}">
                  </div>
                  <div class="form-group">
                    <label for="actioned_by">Actioned by:</label>
                    <input type="text" class="form-control" id="actioned_by" name="actioned_by" value="{{ meeting.actioned_by }}">
                  </div>
                  <div class="form-group">
                    <label for="subsequent_information">Subsequent information:</label>
                    <input type="text" class="form-control" id="subsequent_information" name="subsequent_information" value="{{ meeting.subsequent_information }}">
                  </div>
                  <div class="form-group">
                    <label for="end_time">End time:</label>
                    <input type="text" class="form-control" id="end_time" name="end_time" value="{{ meeting.end_time }}">
                  </div>
                  <button type="submit" class="btn btn-primary">Submit</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}
"""

website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
    content %}
    <form method="POST">
      <br/>
      <h1 align="center">Sign Up</h1>
      <br/>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group">
        <label for="firstName">First Name</label>
        <input
          type="text"
          class="form-control"
          id="firstName"
          name="firstName"
          placeholder="Enter first name"
        />
      </div>
      <div class="form-group">
        <label for="password1">Password</label>
        <input
          type="password"
          class="form-control"
          id="password1"
          name="password1"
          placeholder="Enter password"
        />
      </div>
      <div class="form-group">
        <label for="password2">Password (Confirm)</label>
        <input
          type="password"
          class="form-control"
          id="password2"
          name="password2"
          placeholder="Confirm password"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% endblock %}